### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by Margen67**
Checkout is slow because the repo is ~1GB.

### CODE REVIEW

**Comment by reepblue** [comment]
@Joshua-Ashton @DankParrot Please review this as I haven't the slightest clue what this does.

**Comment by Joshua-Ashton** [comment]
I'm going to provide a proper fix for VPC stuff soon, so that can be removed from the actions.

**Comment by micwoj92** [comment]
When is soon?

**Pull request closed without merging**
