### PR TITLE
Scriptable weapons

### PR DESCRIPTION
**Pull request by SCell555**
Base system from firefight reloaded
Works in single player, save-restore system seems to work OK with custom weapons
No custom weapon entity limit
Custom ammo definition system for custom weapons

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Why is the custom weapon code in HL2? Shouldn't it be its own thing or in the root?

**Comment by SCell555** [comment]
I placed it in HL2 because it custom weapons use hl2 weapon base

**Comment by Joshua-Ashton** [comment]
You should try and remove the HL dependency

**Comment by SCell555** [comment]
But then npcs won't be able to use them

**Comment by Joshua-Ashton** [comment]
You could test if it was a HL2 DLL we are compiling and change the base class based on that.

**Comment by SCell555** [comment]
I could do that

**Comment by SCell555** [comment]
Hopefully I didn't break anything

**Comment by Joshua-Ashton** [comment]
Wouldn't it be easier to put the file that includes custom weapons in the base VPCs rather than in all of the game ones? ;P

**Comment by Joshua-Ashton** [comment]
Sweet.

**Pull request merged**
